### ISSUE TITLE
[!] No podspec found for `vocsy_epub_viewer` in `.symlinks/plugins/vocsy_epub_viewer/ios`

### ISSUE THREAD

**Issue by JuniorFlorentino** [kaushikgodhani/vocsy_epub_viewer#1]
Issue / Feature -
Platform (android, iOS or both) - IOs
Crash / Error - [!] No podspec found for `vocsy_epub_viewer` in `.symlinks/plugins/vocsy_epub_viewer/ios`

Steps to reproduce / Describe in detail - 

execute command "pod install"

[!] No podspec found for `vocsy_epub_viewer` in `.symlinks/plugins/vocsy_epub_viewer/ios`

**Comment by kaushikgodhani** [comment]
Please Update our new version 0.0.6

vocsy_epub_viewer: ^0.0.6

**Comment by kaushikgodhani** [comment]
Use latest version of package
