### ISSUE TITLE
TTS not visible

### ISSUE THREAD

**Issue by Jassa25** [kaushikgodhani/vocsy_epub_viewer#13]
I have enabled the tts during configuration but still it doesn't show on menu bar. Even the all other options are visible.

**Comment by Jassa25** [comment]
Hello , anyone can please help

**Comment by Jassa25** [comment]
The text to speech not working

**Comment by vocsygautam** [comment]
in this package No Option for TTS

**Comment by merihcavdar** [comment]
would you advise how to make the tts option available on the screen please?
