### ISSUE TITLE
How to use the parameters returned by method locaterStream ?

### ISSUE THREAD

**Issue by cqq0920** [kaushikgodhani/vocsy_epub_viewer#14]
EpubViewer.locatorStream.listen((locator) {
      // print('------------------LOCATOR: ${EpubLocator.fromJson(jsonDecode(locator))}')
    });
I find that print doesn't work and I cannot use locater to call some method . It seems that this method can only return pagenum and now can I detect it is the lastpage or not .
there are some parameters in log,such as scrollTolast and DirectionalViewpager. i dont know which method are these belong to?how can I use them ?
anybody help?thx

**Comment by vocsygautam** [comment]
This method is use to get last page Location
