### ISSUE TITLE
Listener not working on android 

### ISSUE THREAD

**Issue by chitraarasu** [kaushikgodhani/vocsy_epub_viewer#18]
VocsyEpub.locatorStream.listen((locator) {
print(locator);
if (int.parse(locator) >= 5) {
VocsyEpub.closeReader();
}
});

Close reader function not exist in package so I added that function. This listener only works on IOS not working on Android. What is the issue?

**Comment by vocsygautam** [comment]
in which version, you are testing package ?

**Comment by chitraarasu** [comment]
I tested again still listener not working please check lister

**Comment by chitraarasu** [comment]
In ios listener prints the chapter number while scrolling the epub. but in android prints like this when a user closes the epub viewer

I/flutter (12703): LOCATOR: {"bookId":"urn:uuid:ba1e1afc-defb-458d-b13b-b21f4e93d12a","href":"/OEBPS/Text/The_Racketeer_split_006.html","created":1670904297508,"locations":{"cfi":"epubcfi(/0!/4/2[filepos38088])"},"title":""}

I want to restrict the users to read only the first chapter of the book. I want to listen to chapter number as it works for ios. In android, the listener works a different way. do you have any solution for this?
