### ISSUE TITLE
doesn't show options to change font

### ISSUE THREAD

**Issue by mariofraga84** [kaushikgodhani/vocsy_epub_viewer#2]
Hi,
Thanks for resuming epub project.

I'm using vocsy_epub_viewer but it doesn't show options to change font. It also doesn't show the font icon next to the title.

how do i make it appear?

**Comment by kaushikgodhani** [comment]
please screenshot and which type of setup you have to do so I will check it and help you to fixed that

**Comment by kaushikgodhani** [comment]
vocsy_epub_viewer: ^1.0.1

Update Latest Version
