### ISSUE TITLE
Search, book mark and font customization are not vissible

### ISSUE THREAD

**Issue by chitraarasu** [kaushikgodhani/vocsy_epub_viewer#22]
A few days back I integrated this package into my app that time the search, bookmark and font customization were visible but now I run the same app but it is not showing this feature please check. But I tried the example app from this package it shows correctly. I am also using the latest version also tried to add this source code in dependency in project also but still not working

**Comment by chitraarasu** [comment]
Please help me to fix this error

**Comment by chitraarasu** [comment]
Finally found a solution flutter_inappwebview. I used this package in my project after the epub viewer package functionalities like search book mark etc were not visible

**Comment by djoks** [comment]
I don't get it. How did you use flutter_inappwebview with this package to get those features to show up?

**Comment by chitraarasu-kirshi** [comment]
Actually, flutter_inappwebview was causing the issue. I used this package in my project, which led to some EPUB functionalities not working properly. I replaced flutter_inappwebview with another webview package, and now there are more options available for EPUB.

**Comment by djoks** [comment]
> Actually, flutter_inappwebview was causing the issue. I used this package in my project, which led to some EPUB functionalities not working properly. I replaced flutter_inappwebview with another webview package, and now there are more options available for EPUB.

I'm currently having an issue on iOS where search and bookmark functionality don't show up like on android. Your comment seems like a potential solution but I'm unable to understand the webview aspect, this is how I load the file in code as per the docs:

```
VocsyEpub.open(
          'bookPath',
           lastLocation: EpubLocator.fromJson({
	   "bookId": "2239",
	   "href": "/OEBPS/ch06.xhtml",
	   "created": 1539934158390,
	   "locations": {
		"cfi": "epubcfi(/0!/4/4[simple_book]/2/2/6)"
	          }
	    }), // first page will open up if the value is null
        );
```
        
At which point did you implement your webview and how did you do it? I would be really grateful if you could help me out on this.

**Comment by chitraarasu** [comment]
This package not working properly on iOS. I have faced issue on android when i use flutter_inappwebview package on same project. Many features in this package worked on android after removing flutter_inappwebview package from project.

If you need epub reader for IOS then you need to integrate folio reader on iOS module using the Method Channel. https://github.com/FolioReader/FolioReaderKit

**Comment by djoks** [comment]
> This package not working properly on iOS. I have faced issue on android when i use flutter_inappwebview package on same project. Many features in this package worked on android after removing flutter_inappwebview package from project.
> 
> If you need epub reader for IOS then you need to integrate folio reader on iOS module using the Method Channel. https://github.com/FolioReader/FolioReaderKit

Oh wow, thanks for the information, I will try that approach! 👍🏾
