### ISSUE TITLE
App Restart while Trying Select Text

### ISSUE THREAD

**Issue by Test1990143** [kaushikgodhani/vocsy_epub_viewer#3]
if the Book have input text Box ,After Enter Text Select the Entered Text App Restart with Following Error.
![2](https://user-images.githubusercontent.com/100760243/180602319-20cb6667-1cc3-4aa8-846a-21bc4c599c40.png)

Error Details:

/FolioWebView( 6557): -> startActionMode
D/FolioWebView( 6557): -> onCreateActionMode
D/FolioWebView( 6557): -> onPrepareActionMode
D/FolioWebView( 6557): -> onGetContentRect
V/ResourceHandler( 6557): Method: GET, Uri: /83821586240571/EPUB/
D/FolioWebView( 6557): -> onDestroyActionMode
D/FolioWebView( 6557): -> dismissPopupWindow -> /EPUB/pr01.xhtml
V/WebViewConsole( 6557): -> getSelectionRect [file:///android_asset/js/Bridge.js:764]
E/WebViewConsole( 6557): Uncaught TypeError: Cannot read property 'left' of null [file:///android_asset/js/Bridge.js:777]
V/FolioAppBarLayout( 6557): -> onApplyWindowInsets
D/AndroidRuntime( 6557): Shutting down VM
E/ResourceHandler( 6557): Exception in get
E/ResourceHandler( 6557): kotlin.KotlinNullPointerException
E/ResourceHandler( 6557): 	at org.readium.r2.streamer.server.handler.ResourceHandler.get(ResourceHandler.kt:51)
E/ResourceHandler( 6557): 	at org.nanohttpd.router.RouterNanoHTTPD$UriResource.process(RouterNanoHTTPD.java:385)
E/ResourceHandler( 6557): 	at org.nanohttpd.router.RouterNanoHTTPD$UriRouter.process(RouterNanoHTTPD.java:597)
E/ResourceHandler( 6557): 	at org.nanohttpd.router.RouterNanoHTTPD.serve(RouterNanoHTTPD.java:672)
E/ResourceHandler( 6557): 	at org.nanohttpd.protocols.http.NanoHTTPD$1.handle(NanoHTTPD.java:376)
E/ResourceHandler( 6557): 	at org.nanohttpd.protocols.http.NanoHTTPD$1.handle(NanoHTTPD.java:372)
E/ResourceHandler( 6557): 	at org.nanohttpd.protocols.http.NanoHTTPD.handle(NanoHTTPD.java:535)
E/ResourceHandler( 6557): 	at org.nanohttpd.protocols.http.HTTPSession.execute(HTTPSession.java:421)
E/ResourceHandler( 6557): 	at org.nanohttpd.protocols.http.ClientHandler.run(ClientHandler.java:75)
E/ResourceHandler( 6557): 	at java.lang.Thread.run(Thread.java:761)
E/AndroidRuntime( 6557): FATAL EXCEPTION: main
E/AndroidRuntime( 6557): Process: com.xsosys.example, PID: 6557
E/AndroidRuntime( 6557): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 6557): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
E/AndroidRuntime( 6557): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 6557): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6557): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
E/AndroidRuntime( 6557): 	... 1 more
E/AndroidRuntime( 6557): Caused by: org.json.JSONException: Value null of type org.json.JSONObject$1 cannot be converted to JSONObject
E/AndroidRuntime( 6557): 	at org.json.JSON.typeMismatch(JSON.java:111)
E/AndroidRuntime( 6557): 	at org.json.JSONObject.<init>(JSONObject.java:160)
E/AndroidRuntime( 6557): 	at org.json.JSONObject.<init>(JSONObject.java:173)
E/AndroidRuntime( 6557): 	at com.folioreader.ui.view.FolioWebView$TextSelectionCb2$onGetContentRect$1.onReceiveValue(FolioWebView.kt:574)
E/AndroidRuntime( 6557): 	at com.folioreader.ui.view.FolioWebView$TextSelectionCb2$onGetContentRect$1.onReceiveValue(FolioWebView.kt:547)
E/AndroidRuntime( 6557): 	at sl.onResult(chromium-Monochrome.aab-stable-424018521:1)
E/AndroidRuntime( 6557): 	at Lr0.run(chromium-Monochrome.aab-stable-424018521:1)
E/AndroidRuntime( 6557): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime( 6557): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 6557): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime( 6557): 	at android.app.ActivityThread.main(ActivityThread.java:6138)
E/AndroidRuntime( 6557): 	... 3 more
I/Process ( 6557): Sending signal. PID: 6557 SIG: 9
Lost connection to device.

**Comment by kaushikgodhani** [comment]
vocsy_epub_viewer: ^1.0.1

Update Latest Version
