### ISSUE TITLE
Getting Error Failed to initialize book

### ISSUE THREAD

**Issue by d2square** [kaushikgodhani/vocsy_epub_viewer#35]
Failed to initialize book
E/FolioActivity( 3558): java.lang.Exception: -> Unknown book file extension `EPUB'`
E/FolioActivity( 3558): 	at com.folioreader.ui.activity.FolioActivity.initBook(FolioActivity.kt:603)
E/FolioActivity( 3558): 	at com.folioreader.ui.activity.FolioActivity.setupBook(FolioActivity.kt:577)
E/FolioActivity( 3558): 	at com.folioreader.ui.activity.FolioActivity.onCreate(FolioActivity.kt:316)
E/FolioActivity( 3558): 	at android.app.Activity.performCreate(Activity.java:7893)
E/FolioActivity( 3558): 	at android.app.Activity.performCreate(Activity.java:7880)
E/FolioActivity( 3558): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
E/FolioActivity( 3558): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3286)
E/FolioActivity( 3558): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3460)
E/FolioActivity( 3558): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E/FolioActivity( 3558): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/FolioActivity( 3558): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/FolioActivity( 3558): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
E/FolioActivity( 3558): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/FolioActivity( 3558): 	at android.os.Looper.loop(Looper.java:224)
E/FolioActivity( 3558): 	at android.app.ActivityThread.main(ActivityThread.java:7590)
E/FolioActivity( 3558): 	at java.lang.reflect.Method.invoke(Native Method)
E/FolioActivity( 3558): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/FolioActivity( 3558): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/FolioActivity( 3558): Caused by: java.lang.IllegalArgumentException: No enum constant org.readium.r2.shared.Publication.EXTENSION.EPUB'
E/FolioActivity( 3558): 	at java.lang.Enum.valueOf(Enum.java:257)
E/FolioActivity( 3558): 	at org.readium.r2.shared.Publication$EXTENSION.valueOf(Unknown Source:2)
E/FolioActivity( 3558): 	at com.folioreader.ui.activity.FolioActivity.initBook(FolioActivity.kt:601)
E/FolioActivity( 3558): 	... 17 more

**Comment by kaushikgodhani** [comment]
SORRY FOR DELAY

PLEASE CHECK THIS NEW VERSION "vocsy_epub_viewer: ^3.0.0" AND GIVE YOUR REVIEW.
