### ISSUE TITLE
Some Books Not Render.

### ISSUE THREAD

**Issue by Test1990143** [kaushikgodhani/vocsy_epub_viewer#4]
![book_error](https://user-images.githubusercontent.com/100760243/180602819-3caa8c21-8b3e-4915-a376-6117a9ce9cdb.png)
Some Books Not Render Show Below Error.

Error:
![book_error](https://user-images.githubusercontent.com/100760243/180602815-7bfeca6a-9044-4327-8549-ce02019c26f9.png)
"Below is a rendering of the page up to the first error"

**Comment by kaushikgodhani** [comment]
vocsy_epub_viewer: ^1.0.1

Update Latest Version
