### ISSUE TITLE
Release Mode Bug

### ISSUE THREAD

**Issue by AvniErtas** [kaushikgodhani/vocsy_epub_viewer#57]
Debug is okey but Release mode not working. 
A package dependency is causing a problem called fuel

**Comment by Dhruvin-5923** [comment]
I have same issue in debug mode also

**Comment by kaushikgodhani** [comment]
SORRY FOR DELAY

PLEASE CHECK THIS NEW VERSION "vocsy_epub_viewer: ^3.0.0" AND GIVE YOUR REVIEW.

**Comment by AvniErtas** [comment]
Hello,

Thanks for your effort. I updated and it works,

Best Regards,
Avni
________________________________
Gönderen: Kaushikkumar Godhani ***@***.***>
Gönderildi: 2 Eylül 2024 Pazartesi 12:26
Kime: kaushikgodhani/vocsy_epub_viewer ***@***.***>
Bilgi: AvniErtas ***@***.***>; Author ***@***.***>
Konu: Re: [kaushikgodhani/vocsy_epub_viewer] Release Mode Bug (Issue #57)


SORRY FOR DELAY

PLEASE CHECK THIS NEW VERSION "vocsy_epub_viewer: ^3.0.0" AND GIVE YOUR REVIEW.

**Comment by AvniErtas** [comment]
Thanks for your effort. I updated and it works,
