### ISSUE TITLE
Error in Android version

### ISSUE THREAD

**Issue by alexandre-castro** [kaushikgodhani/vocsy_epub_viewer#59]
**Can you help me ?**

> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.kittinunf.fuel:fuel:1.15.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/kittinunf/fuel/fuel/1.15.0/fuel-1.15.0.pom
       - https://repo.maven.apache.org/maven2/com/github/kittinunf/fuel/fuel/1.15.0/fuel-1.15.0.pom
       - https://storage.googleapis.com/download.flutter.io/com/github/kittinunf/fuel/fuel/1.15.0/fuel-1.15.0.pom
       - https://jcenter.bintray.com/com/github/kittinunf/fuel/fuel/1.15.0/fuel-1.15.0.pom
       - https://jitpack.io/com/github/kittinunf/fuel/fuel/1.15.0/fuel-1.15.0.pom
     Required by:
         project :app > project :vocsy_epub_viewer > com.github.kaushikgodhani:vocsy_epub_viewer_android_folioreader:V4 > com.github.codetoart:r2-shared-kotlin:1.0.4-2

**Comment by kaushikgodhani** [comment]
SORRY FOR DELAY

PLEASE CHECK THIS NEW VERSION "vocsy_epub_viewer: ^3.0.0" AND GIVE YOUR REVIEW.

**Comment by alexandre-castro** [comment]
Hi, YES ! It's works now !
Thank you !!!
