### ISSUE TITLE
There was a problem with  compileSdkVersion 33

### ISSUE THREAD

**Issue by 0MohamedHisham0** [kaushikgodhani/vocsy_epub_viewer#6]
android:exported needs to be explicitly specified for element <activity#com.folioreader.ui.activity.SearchActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

**Comment by mariofraga84** [comment]
I have exactly the same problem.
did anyone manage to solve it?

**Comment by kaushikgodhani** [comment]
@mariofraga84 @0MohamedHisham0  we will update soon

**Comment by MohamadAbdUlaziz938** [comment]
@0MohamedHisham0
@mariofraga84 
you have to add eported:true for every activity in folio reader , I faced the problem lastly and fix it by rewriting every activity used in #folioreader in my project manifest then add to every activity exported:true .
good luck.

**Comment by mariofraga84** [comment]
solution:
 in AndroidManifest
add  android:exported="true" in 
  `<activity
            android:name=".MainActivity"
 android:exported="true" 
> `
 and add:
 `       <activity android:name="com.folioreader.ui.activity.SearchActivity"
           android:exported="true"
           tools:node="merge" />`

**Comment by mariofraga84** [comment]
solution

add  android:exported="true" in 
<activity
            android:name=".MainActivity"


and add 

<activity android:name="com.folioreader.ui.activity.SearchActivity"
           android:exported="true"
           tools:node="merge" />

**Comment by 0MohamedHisham0** [comment]
This Worked for me
