### ISSUE TITLE
Dual screen opening

### ISSUE THREAD

**Issue by anil5387** [kaushikgodhani/vocsy_epub_viewer#61]
When I trying to open any epub file it is getting opened in new screen.

 ListView.separated(
          itemBuilder: (BuildContext context, int index) {
            return ListTile(
              title: Text(itemTitle[index]),
              onTap: () async {

              MyRouter.pushPage(
                  context,
                  VocsyEpub.openAsset('assets/myepub.epub',
                          lastLocation: EpubLocator.fromJson({
                            "bookId": "2239",
                            "href": "/OEBPS/ch06.xhtml",
                            "created": 1539934158390,
                            "locations": {"cfi": "epubcfi(/0!/4/4[simple_book]/2/2/6)"}
                          }))
                      as Widget);
            },
            );
          },
          separatorBuilder: (BuildContext context, int index) {
        return Divider();
      }, 
          itemCount: itemTitle.length
          ),
      ),
    );

**Comment by rinkeshjain** [comment]
Please check your AndroidManifest file if you're using taskAffinity  ```android:taskAffinity```, you need to remove it

**Purpose of taskAffinity**

**Task Affinity**: It defines which task an activity prefers to belong to. By default, all activities in an application have the same task affinity, which is the application's package name.

**Custom Task Affinity**: You can assign a different task affinity to an activity to make it start in a **different task or to group** certain activities together in a specific task.

**Comment by anil5387** [comment]
Thank you so much @rinkeshjain  it is working now.
