### ISSUE TITLE
Crash logged on crashlytics: SwiftEpubKittyPlugin.swift line 456

### ISSUE THREAD

**Issue by neeluagrawal04** [kaushikgodhani/vocsy_epub_viewer#8]
crash logged on crashlytics:
SwiftEpubKittyPlugin.swift line 456
SwiftEpubViewerPlugin.open(epubPath:)

Crashed: com.apple.main-thread
0  vocsy_epub_viewer              0x8dd4 SwiftEpubViewerPlugin.open(epubPath:) + 456 (SwiftEpubKittyPlugin.swift:456)
1  vocsy_epub_viewer              0x9908 specialized SwiftEpubViewerPlugin.handle(_:result:) + 1668 (<compiler-generated>:1668)
2  vocsy_epub_viewer              0x8920 @objc SwiftEpubViewerPlugin.handle(_:result:) + 72 (<compiler-generated>:72)
3  Flutter                        0x577e00 (Missing UUID 06c0b1046d24347198d4326e87347d68)
4  Flutter                        0x43e8c (Missing UUID 06c0b1046d24347198d4326e87347d68)
5  libdispatch.dylib              0x24b4 _dispatch_call_block_and_release + 32
6  libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
7  libdispatch.dylib              0x127f4 _dispatch_main_queue_drain + 928
8  libdispatch.dylib              0x12444 _dispatch_main_queue_callback_4CF + 44
9  CoreFoundation                 0x9aa08 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
10 CoreFoundation                 0x7c368 __CFRunLoopRun + 2036
11 CoreFoundation                 0x811e4 CFRunLoopRunSpecific + 612
12 GraphicsServices               0x1368 GSEventRunModal + 164
13 UIKitCore                      0x3a2d88 -[UIApplication _run] + 888
14 UIKitCore                      0x3a29ec UIApplicationMain + 340
15 Runner                         0x8064 main + 16 (AppDelegate.swift:16)
16 ???                            0x1a84b1948 (Missing)

**Comment by kaushikgodhani** [comment]
vocsy_epub_viewer: ^1.0.1

Update Latest Version
